#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the hourglassSum function below.
def hourglassSum(arr):
    sumArr = []
    for i in range(4):
        for y in range(4):
            for z in range(i+1, i+2):
                for t in range(y+1, y+2):
                    for u in range(i+2, i+3):
                        for v in range(y, y+1):
                            result = sum(arr[i][y:y+3]) + arr[z][t] + sum(arr[u][v:v+3])
                            sumArr.append(result)
    return max(sumArr)
                

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
