#!/bin/python3

import os
import sys

#
# Complete the getTotalX function below.
#
def getTotalX(a, b):
    global count
    count = 0
    myList = []
    x = max(a)
    y = min(b)
    maximum = y // x
    for i in range(1,maximum+1,1):
        myList.append(int(x*i))
    for z in myList:
        if all(s % z == 0 for s in b) and all(z % p == 0 for p in a):
            count += 1
    return count
    
if __name__ == '__main__':
    f = open(os.environ['OUTPUT_PATH'], 'w')

    nm = input().split()

    n = int(nm[0])

    m = int(nm[1])

    a = list(map(int, input().rstrip().split()))

    b = list(map(int, input().rstrip().split()))

    total = getTotalX(a, b)

    f.write(str(total) + '\n')

    f.close()
