#!/bin/python3

import sys

def solve(a0, a1, a2, b0, b1, b2):
    alice_score = 0
    bob_score = 0
    alice = [a0,a1,a2]
    bob = [b0,b1,b2]
    for i in range(3):
        if alice[i] > bob[i]:
            alice_score += 1
        elif alice[i] < bob[i]:
            bob_score += 1
    return alice_score,bob_score

a0, a1, a2 = input().strip().split(' ')
a0, a1, a2 = [int(a0), int(a1), int(a2)]
b0, b1, b2 = input().strip().split(' ')
b0, b1, b2 = [int(b0), int(b1), int(b2)]
result = solve(a0, a1, a2, b0, b1, b2)
print (" ".join(map(str, result)))


