#!/bin/python3

import sys
import re

pattern1 = r"^[a-z]{1,20}$"
pattern2 = r"^[a-z]{1,20}@[a-z]{0,20}(gmail.com)$"
myList = []
N = int(input().strip())
for a0 in range(N):
    firstName,emailID = input().strip().split(' ')
    firstName,emailID = [str(firstName),str(emailID)]
    if re.match(pattern1,firstName) and re.match(pattern2,emailID):
        myList.append(firstName)
myList.sort()
for i in myList:
    print(i)
