#!/bin/python3
import sys
n = int(input().strip())
a = list(map(int, input().strip().split(' ')))
b = len(a)
count = 0
for i in range(b): 
    for y in range(b-1,0,-1):
        if a[y] < a[y-1]:
            a[y],a[y-1] = a[y-1],a[y]
            count += 1
print("Array is sorted in "+str(count)+" swaps.")
print("First Element: "+str(a[0]))
print("Last Element: "+str(a[-1]))
