#!/bin/python3

import sys

def diagonalDifference(a):
    sum1 = 0
    sum2 = 0
    for i in range(n):
        sum1 += a[i][i]
    for z in range(n):
        sum2 += a[z][n-z-1]
    return abs(sum1-sum2)

if __name__ == "__main__":
    n = int(input().strip())
    a = []
    for a_i in range(n):
       a_t = [int(a_temp) for a_temp in input().strip().split(' ')]
       a.append(a_t)
    result = diagonalDifference(a)
    print(result)
