#!/bin/python3

import sys
from itertools import combinations

def divisibleSumPairs(n, k, ar):
    count = 0
    all_combinations = list(combinations(ar,2))
    for z in all_combinations:
        if sum(z) % k == 0:
            count += 1
    return count

n, k = input().strip().split(' ')
n, k = [int(n), int(k)]
ar = list(map(int, input().strip().split(' ')))
result = divisibleSumPairs(n, k, ar)
print(result)
