#!/bin/python3
import sys
def solve(n, p):
    if n % 2 != 0:
        return min((n-p)//2,p//2)
    return min((n+1-p)//2,p//2)
n = int(input().strip())
p = int(input().strip())
result = solve(n, p)
print(result)
