#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the jumpingOnClouds function below.
def jumpingOnClouds(c):
    pos, count = 0, 0
    while pos <= len(c) - 2:
        if pos == (len(c) - 2):
            count += 1
            pos += 1
        else:
            if c[pos+2] == 1:
                pos += 1
                count += 1
            else:
                pos += 2
                count += 1
    return count
        
        

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    c = list(map(int, input().rstrip().split()))

    result = jumpingOnClouds(c)

    fptr.write(str(result) + '\n')

    fptr.close()
