#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the luckBalance function below.
def luckBalance(k, contests):
    luck = 0
    loseList = []
    for contest in contests:
        if contest[1] == 0:
            luck += contest[0]
        else:
            loseList.append(contest[0])
    loseList.sort(reverse=True)
    if k <= len(loseList):
        for elem in loseList[0:k]:
            luck += elem
    elif k > len(loseList):
        for elem in loseList:
            luck += elem
    if k < len(loseList):
        for elem in loseList[k:len(loseList)]:
            luck -= elem
    return luck

    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    nk = input().split()

    n = int(nk[0])

    k = int(nk[1])

    contests = []

    for _ in range(n):
        contests.append(list(map(int, input().rstrip().split())))

    result = luckBalance(k, contests)

    fptr.write(str(result) + '\n')

    fptr.close()
