#!/bin/python3

import math
import os
import random
import re
import sys
from itertools import combinations

# Complete the minimumAbsoluteDifference function below.
def minimumAbsoluteDifference(arr):
    diff = 9999999999999
    arr.sort()
    for i in range(len(arr)-1):
        if math.fabs(arr[i]-arr[i+1]) < diff:
            diff = math.fabs(arr[i]-arr[i+1])
    return int(diff)




if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    result = minimumAbsoluteDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
