#!/bin/python3

import sys

def plusMinus(arr):
    positive = [i for i in arr if i>0]
    negative = [i for i in arr if i<0]
    zero = [i for i in arr if i==0]
    positive_percentage = len(positive) / len(arr)
    negative_percentage = len(negative) / len(arr)
    zero_percentage = len(zero) / len(arr)
    print(positive_percentage)
    print(negative_percentage)
    print(zero_percentage)

if __name__ == "__main__":
    n = int(input().strip())
    arr = list(map(int, input().strip().split(' ')))
    plusMinus(arr)
