#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the repeatedString function below.
def repeatedString(s, n):
    length = len(s) # length of string
    numberOfRepeat = math.floor(n / length)
    repeat = numberOfRepeat * s.count("a")
    if numberOfRepeat * len(s) < n:
        remainingLetters = n - numberOfRepeat * len(s)
        repeat += s[0:remainingLetters].count("a")
    return repeat
    

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
