#!/bin/python3

import sys

def sockMerchant(n, ar):
    mySet = set(ar)
    count = 0
    for y in mySet:
        count += (ar.count(y) // 2)
    return count
        
        

n = int(input().strip())
ar = list(map(int, input().strip().split(' ')))
result = sockMerchant(n, ar)
print(result)
