#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the minimumNumber function below.
def minimumNumber(n, password):
    # Return the minimum number of characters to make the password strong
    characterNumber = 0
    if not re.search(r"[0-9]",password):
        characterNumber += 1
    if not re.search(r"[a-z]",password):
        characterNumber += 1
    if not re.search(r"[A-Z]",password):
        characterNumber += 1
    if not re.search(r"[!@#$%^&*()\-+]",password):
        characterNumber += 1
    return max(characterNumber,6-n)
       

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    password = input()

    answer = minimumNumber(n, password)

    fptr.write(str(answer) + '\n')

    fptr.close()
