#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the viralAdvertising function below.
def viralAdvertising(n):
    day = 1
    shared = 5
    liked = 2
    cumulative = 2
    while day < n:
        shared = math.floor(shared / 2) * 3
        liked = math.floor(shared / 2)
        cumulative += liked
        day += 1
    return cumulative



if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    result = viralAdvertising(n)

    fptr.write(str(result) + '\n')

    fptr.close()
